applications:
- guillotina.contrib.redis
- guillotina.contrib.swagger
allow_register: true
cache:
  driver: guillotina.contrib.redis
  updates_channel: guillotina
auth_extractors:
- guillotina.auth.extractors.BearerAuthPolicy
- guillotina.auth.extractors.BasicAuthPolicy
- guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
- guillotina.auth.validators.JWTValidator
- guillotina.auth.validators.SaltedHashPasswordValidator
databases:
  data:
    storage: postgresql
    transaction_strategy: dbresolve_readcommitted
    dsn: postgresql://postgres:postgres@localhost:5432/data?sslmode=disable
    pool_size: 40
    autovacuum: true
    read_only: false
    statement_cache_size: 100
    max_cached_statement_lifetime: 300
store_json: true
host: 0.0.0.0
port: 8080
redis:
  host: localhost
  port: 6379
root_user:
  password: root
cors:
  allow_origin:
  - http://localhost:3000
  - http://localhost:8080
  allow_methods:
  - GET
  - POST
  - DELETE
  - HEAD
  - PATCH
  - PUT
  - OPTIONS
  allow_headers:
  - "*"
  expose_headers:
  - "*"
  allow_credentials: true
  max_age: 3660

load_catalog: True
